# Generated by Django 3.0.2 on 2020-01-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginModel',
        ),
    ]
