# Generated by Django 3.0.2 on 2020-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20200114_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
